description: Masking for Employee recods
rules:
  -
    matcher: ssn
    masker:
      type: ssn
  -
    matcher: birthday
    masker:
      type: birthday
      range: 10
      sticky: true
      salt: d3fw
  -
    matcher: email
    masker:
      type: email
  -
    matcher: phone
    masker:
      type: phone
